## 00. Visualization

In [1]:
import pandas as pd
import dtale

# Function to show df in D-Tale
def show_df_in_dtale(df):
    instance = dtale.show(df)
    instance.kill()
    d = dtale.show(df, enable_custom_filters=True)
    print(f"D-Tale running on: {d._main_url}")

#### **Processed for training**

In [3]:
df = pd.read_csv("../../data/Competition/processed_for_training/competition_processed_for_training_week_h6_t_plus_1.csv", sep=";")
df

,product,store,week,value,fourier_sin_1,fourier_cos_1,fourier_sin_2,fourier_cos_2,fourier_sin_3,fourier_cos_3,...,ewm_mean_13_scaled,ewm_mean_26_scaled,rolling_slope_4_scaled,rolling_slope_8_scaled,rolling_slope_13_scaled,last_year_mean_3_scaled,sample_weight,scale_factor,target_t_plus_1,target_scaled_t_plus_1
0,0,61,2021-04-12,0.0,0.972399,-0.233325,-0.453769,-0.891119,-0.760648,0.649165,...,0.000000,0.000000,NaN,NaN,NaN,NaN,0.113864,1.000000,0.0,0.000000
1,0,61,2021-04-19,0.0,0.937328,-0.348448,-0.653220,-0.757168,-0.482102,0.876115,...,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.115392,1.000000,0.0,0.000000
2,0,61,2021-04-26,0.0,0.888682,-0.458524,-0.814965,-0.579511,-0.141319,0.989964,...,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.116940,1.000000,1.0,1.000000
3,0,61,2021-05-03,1.0,0.827164,-0.561960,-0.929667,-0.368402,0.217707,0.976014,...,0.142857,0.074074,0.300000,0.300000,0.300000,NaN,0.118510,1.000000,0.0,0.000000
4,0,61,2021-05-10,0.0,0.753667,-0.657257,-0.990705,-0.136027,0.548628,0.836066,...,0.122449,0.068587,0.100000,0.100000,0.100000,NaN,0.120100,1.000000,1.0,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98231,99,63,2024-04-29,3.0,0.827164,-0.561960,-0.929667,-0.368402,0.217707,0.976014,...,0.868847,0.960387,0.054639,-0.035776,-0.106576,1.548110,0.948078,3.660377,5.0,1.365979
98232,99,63,2024-05-06,5.0,0.753667,-0.657257,-0.990705,-0.136027,0.548628,0.836066,...,0.944735,0.995562,0.329534,0.058845,-0.051301,1.922280,0.960800,3.641509,5.0,1.373057
98233,99,63,2024-05-13,5.0,0.669254,-0.743034,-0.994556,0.104199,0.808725,0.588187,...,1.032678,1.050746,0.225532,0.120821,0.009294,1.503546,0.973693,3.547170,4.0,1.127660
98234,99,63,2024-05-20,4.0,0.575147,-0.818050,-0.940998,0.338411,0.964420,0.264376,...,1.051841,1.062093,0.085027,0.145085,-0.009344,0.755793,0.986759,3.528302,6.0,1.700535
98235,99,63,2024-05-27,6.0,0.472711,-0.881217,-0.833123,0.553088,0.995613,-0.093564,...,1.114707,1.080495,0.055208,0.144593,0.018201,0.276042,1.000000,3.622642,NaN,NaN

In [4]:
df.columns

Index(['product', 'store', 'week', 'value', 'fourier_sin_1', 'fourier_cos_1',
       'fourier_sin_2', 'fourier_cos_2', 'fourier_sin_3', 'fourier_cos_3',
       'last_year_ratio_3', 'nonzero_rate_4', 'nonzero_rate_8',
       'nonzero_rate_13', 'nonzero_rate_26', 'nonzero_rate_52', 'spike_rate_8',
       'spike_rate_13', 'spike_rate_26', 'log_scale_factor', 'lag_0', 'lag_1',
       'lag_2', 'lag_3', 'lag_4', 'lag_12', 'lag_25', 'lag_51',
       'rolling_mean_3', 'rolling_std_3', 'rolling_mean_4', 'rolling_std_4',
       'rolling_mean_5', 'rolling_std_5', 'rolling_mean_8', 'rolling_std_8',
       'rolling_mean_13', 'rolling_std_13', 'rolling_mean_26',
       'rolling_std_26', 'rolling_mean_52', 'rolling_std_52', 'ewm_mean_4',
       'ewm_mean_8', 'ewm_mean_13', 'ewm_mean_26', 'rolling_slope_4',
       'rolling_slope_8', 'rolling_slope_13', 'last_year_mean_3',
       'lag_0_scaled', 'lag_1_scaled', 'lag_2_scaled', 'lag_3_scaled',
       'lag_4_scaled', 'lag_12_scaled', 'lag_25_scaled', 'lag_51_scaled',
       'rolling_mean_3_scaled', 'rolling_std_3_scaled',
       'rolling_mean_4_scaled', 'rolling_std_4_scaled',
       'rolling_mean_5_scaled', 'rolling_std_5_scaled',
       'rolling_mean_8_scaled', 'rolling_std_8_scaled',
       'rolling_mean_13_scaled', 'rolling_std_13_scaled',
       'rolling_mean_26_scaled', 'rolling_std_26_scaled',
       'rolling_mean_52_scaled', 'rolling_std_52_scaled', 'ewm_mean_4_scaled',
       'ewm_mean_8_scaled', 'ewm_mean_13_scaled', 'ewm_mean_26_scaled',
       'rolling_slope_4_scaled', 'rolling_slope_8_scaled',
       'rolling_slope_13_scaled', 'last_year_mean_3_scaled', 'sample_weight',
       'scale_factor', 'target_t_plus_1', 'target_scaled_t_plus_1'],
      dtype='str')

In [ ]:
# Columns that end with "_scaled"
scaled_cols = [col for col in df.columns if col.endswith("_scaled")]

# Same column names without "_scaled"
original_cols_to_drop = [col.removesuffix("_scaled") for col in scaled_cols]

# Keep only those that actually exist in the original df
original_cols_to_drop = [col for col in original_cols_to_drop if col in df.columns]

# Drop them from df
df = df.drop(columns=original_cols_to_drop)

In [5]:
show_df_in_dtale(df)

2026-06-10 17:01:24,282 - INFO     - Executing shutdown...
2026-06-10 17:01:24,283 - INFO     - Not running with the Werkzeug Server, exiting by searching gc for BaseWSGIServer
2026-06-10 17:01:25,536 - WARNING  - Custom filtering enabled. Custom filters are vulnerable to code injection attacks, please only use in trusted environments.

D-Tale running on: http://PC-104:40000/dtale/main/1

2026-06-10 18:03:06,278 - INFO     - Executing shutdown due to inactivity...
2026-06-10 18:03:10,621 - INFO     - Executing shutdown...
2026-06-10 18:03:10,625 - INFO     - Not running with the Werkzeug Server, exiting by searching gc for BaseWSGIServer

#### **Predictions**

In [2]:
#df_products = pd.read_excel("../../data/Competition/raw/competition - Aquiles_products.xlsx")
df = pd.read_csv("../../results/competition_catboost_predictions_week_h6_default_params.csv", sep=";")
df

,product,store,datetime,train_val_test,fourier_sin_1,fourier_cos_1,fourier_sin_2,fourier_cos_2,fourier_sin_3,fourier_cos_3,...,lag_21_scaled,lag_21,lag_47_scaled,lag_47,lag_7_scaled,lag_7,lag_20_scaled,lag_20,lag_46_scaled,lag_46
0,0,61,2021-04-12,train,0.972399,-0.233325,-0.453769,-0.891119,-0.760648,0.649165,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,61,2021-04-12,train,0.972399,-0.233325,-0.453769,-0.891119,-0.760648,0.649165,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,61,2021-04-12,train,0.972399,-0.233325,-0.453769,-0.891119,-0.760648,0.649165,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,61,2021-04-12,train,0.972399,-0.233325,-0.453769,-0.891119,-0.760648,0.649165,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,61,2021-04-12,train,0.972399,-0.233325,-0.453769,-0.891119,-0.760648,0.649165,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576832,99,63,2024-05-06,train,0.753667,-0.657257,-0.990705,-0.136027,0.548628,0.836066,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
576833,99,63,2024-05-06,train,0.753667,-0.657257,-0.990705,-0.136027,0.548628,0.836066,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
576834,99,63,2024-05-13,train,0.669254,-0.743034,-0.994556,0.104199,0.808725,0.588187,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
576835,99,63,2024-05-13,train,0.669254,-0.743034,-0.994556,0.104199,0.808725,0.588187,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
576836,99,63,2024-05-20,train,0.575147,-0.818050,-0.940998,0.338411,0.964420,0.264376,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
show_df_in_dtale(df)

c:\Users\jmi\AppData\Local\miniconda3\envs\time_series_auto\Lib\site-packages\dtale\utils.py:868: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data = data.reset_index(drop=drop_index)
2026-06-22 12:12:55,283 - INFO     - Executing shutdown...
2026-06-22 12:12:55,285 - INFO     - Not running with the Werkzeug Server, exiting by searching gc for BaseWSGIServer
c:\Users\jmi\AppData\Local\miniconda3\envs\time_series_auto\Lib\site-packages\dtale\utils.py:868: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data = data.reset_index(drop=drop_index)
2026-06-22 12:13:00,308 - WARNING  - Custom filtering enabled. Custom filters are vulnerable to code injection attacks, please only use in trusted environments.

D-Tale running on: http://PC-104:40000/dtale/main/1

2026-06-22 13:36:59,680 - INFO     - Executing shutdown due to inactivity...
2026-06-22 13:37:03,995 - INFO     - Executing shutdown...
2026-06-22 13:37:03,998 - INFO     - Not running with the Werkzeug Server, exiting by searching gc for BaseWSGIServer

In [9]:
#df_products = pd.read_excel("../../data/Competition/raw/competition - Aquiles_products.xlsx")
df = pd.read_csv("../../results/competition_catboost_predictions_month_h6_moderate_params.csv", sep=";")
df

,product,store,datetime,train_val_test,year,week_of_year,month_of_year,quarter_of_year,fourier_sin_1,fourier_cos_1,...,lag_3_scaled,lag_3,lag_9_scaled,lag_9,lag_8_scaled,lag_8,lag_7_scaled,lag_7,lag_6_scaled,lag_6
0,0,61,2021-04-01,train,2021,13,4,2,0.866025,-5.000000e-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,61,2021-04-01,train,2021,13,4,2,0.866025,-5.000000e-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,61,2021-04-01,train,2021,13,4,2,0.866025,-5.000000e-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,61,2021-04-01,train,2021,13,4,2,0.866025,-5.000000e-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,61,2021-04-01,train,2021,13,4,2,0.866025,-5.000000e-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123988,99,63,2024-02-01,train,2024,5,2,1,0.866025,5.000000e-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123989,99,63,2024-02-01,train,2024,5,2,1,0.866025,5.000000e-01,...,1.252747,19.0,1.582418,24.0,NaN,NaN,NaN,NaN,NaN,NaN
123990,99,63,2024-03-01,train,2024,9,3,1,1.000000,6.123234e-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123991,99,63,2024-03-01,train,2024,9,3,1,1.000000,6.123234e-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123992,99,63,2024-04-01,train,2024,14,4,2,0.866025,-5.000000e-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
show_df_in_dtale(df)

c:\Users\jmi\AppData\Local\miniconda3\envs\time_series_auto\Lib\site-packages\dtale\utils.py:868: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data = data.reset_index(drop=drop_index)
2026-06-11 14:03:08,972 - INFO     - Executing shutdown...
2026-06-11 14:03:08,980 - INFO     - Not running with the Werkzeug Server, exiting by searching gc for BaseWSGIServer
c:\Users\jmi\AppData\Local\miniconda3\envs\time_series_auto\Lib\site-packages\dtale\utils.py:868: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data = data.reset_index(drop=drop_index)
2026-06-11 14:03:10,604 - WARNING  - Custom filtering enabled. Custom filters are vulnerable to code injection attacks, please only use in trusted environments.

D-Tale running on: http://PC-104:40000/dtale/main/1