## 02. Raw creation

Saves the original data in raw

In [3]:
import pandas as pd
import dtale

# Function to show df in D-Tale
def show_df_in_dtale(df):
    instance = dtale.show(df)
    instance.kill()
    d = dtale.show(df, enable_custom_filters=True)
    print(f"D-Tale running on: {d._main_url}")

In [ ]:
#df_products = pd.read_excel("../../data/competition/raw/competition - Aquiles_products.xlsx")
df = pd.read_csv("../../data/competition/raw/Week 8 - 2024-06-03 - Sales.csv")
df

,Store,Product,2021-04-12,2021-04-19,2021-04-26,2021-05-03,2021-05-10,2021-05-17,2021-05-24,2021-05-31,...,2024-04-01,2024-04-08,2024-04-15,2024-04-22,2024-04-29,2024-05-06,2024-05-13,2024-05-20,2024-05-27,2024-06-03
0,0,126,0.0,0.0,3.0,3.0,0.0,1.0,1.0,0.0,...,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,4.0
1,0,182,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,2.0,1.0,1.0
2,1,124,13.0,4.0,10.0,5.0,1.0,2.0,3.0,4.0,...,9.0,7.0,10.0,8.0,14.0,15.0,13.0,9.0,8.0,8.0
3,2,124,5.0,5.0,12.0,16.0,10.0,8.0,10.0,9.0,...,13.0,2.0,8.0,6.0,16.0,17.0,15.0,15.0,14.0,10.0
4,2,126,0.0,0.0,6.0,5.0,7.0,4.0,1.0,2.0,...,3.0,2.0,0.0,0.0,0.0,2.0,0.0,2.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,64,193,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,4.0,0.0,0.0,2.0,1.0,0.0
595,64,238,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,1.0,1.0,1.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0
596,65,126,5.0,2.0,3.0,3.0,2.0,6.0,2.0,3.0,...,16.0,0.0,4.0,4.0,4.0,4.0,5.0,0.0,5.0,8.0
597,66,124,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,3.0,7.0,10.0,6.0,5.0,6.0,9.0,10.0,3.0
598,66,126,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,3.0,4.0,9.0,0.0,3.0,0.0,8.0,5.0

In [5]:
df_melted = df.melt(
    id_vars=['Store', 'Product'],
    var_name='datetime',
    value_name='value'
)

df_melted['datetime'] = pd.to_datetime(df_melted['datetime'])

df_melted

       Store  Product   datetime  value
0          0      126 2021-04-12    0.0
1          0      182 2021-04-12    0.0
2          1      124 2021-04-12   13.0
3          2      124 2021-04-12    5.0
4          2      126 2021-04-12    0.0
...      ...      ...        ...    ...
98830     64      193 2024-06-03    0.0
98831     64      238 2024-06-03    0.0
98832     65      126 2024-06-03    8.0
98833     66      124 2024-06-03    3.0
98834     66      126 2024-06-03    5.0

[98835 rows x 4 columns]

In [6]:
df_melted.to_parquet(
    "../../data/competition/raw/competition_raw.parquet",
    index=False,
    engine="pyarrow",
)

In [7]:
show_df_in_dtale(df_melted)

2026-06-10 11:31:53,960 - INFO     - Executing shutdown...
2026-06-10 11:31:53,962 - INFO     - Not running with the Werkzeug Server, exiting by searching gc for BaseWSGIServer
2026-06-10 11:31:54,924 - WARNING  - Custom filtering enabled. Custom filters are vulnerable to code injection attacks, please only use in trusted environments.

D-Tale running on: http://PC-104:40000/dtale/main/1

In [10]:
df_melted[['Store', 'Product']].value_counts()

Store  Product
0      126        165
       182        165
1      124        165
2      124        165
       126        165
                 ...
64     193        165
       238        165
65     126        165
66     124        165
       126        165
Name: count, Length: 599, dtype: int64

In [ ]:
df_melted['value'].isna().sum()

np.int64(0)

2026-06-10 12:49:08,374 - INFO     - Executing shutdown due to inactivity...
2026-06-10 12:49:12,622 - INFO     - Executing shutdown...
2026-06-10 12:49:12,628 - INFO     - Not running with the Werkzeug Server, exiting by searching gc for BaseWSGIServer