## 00. Visualization

In [19]:
import pandas as pd
import dtale

# Function to show df in D-Tale
def show_df_in_dtale(df):
    instance = dtale.show(df)
    instance.kill()
    d = dtale.show(df, enable_custom_filters=True)
    print(f"D-Tale running on: {d._main_url}")

#### **Processed for training**

In [ ]:
df = pd.read_csv("../../data/Lecta/processed_for_training/lecta_processed_for_training_month_h6_t_plus_1.csv", sep=";")
df

,code,warehouse,month,value,momentum_ratio_1,momentum_ratio_4,year,week_of_year,month_of_year,quarter_of_year,...,rolling_slope_3_scaled,rolling_slope_6_scaled,rolling_slope_12_scaled,last_year_mean_3_scaled,last_year_median_3_scaled,spike_prior_median_6_scaled,spike_prior_mad_6_scaled,sample_weight,target_t_plus_1,target_scaled_t_plus_1
0,40000892,1201,2023-12-01,3686.4,NaN,NaN,2023,48,12,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.198519,6912.0,1.875000
1,40000892,1201,2024-01-01,6912.0,1.875000,NaN,2024,1,1,1,...,6.086957e-01,0.608696,0.608696,NaN,NaN,NaN,NaN,0.210549,1843.2,0.347826
2,40000892,1201,2024-02-01,1843.2,0.266667,NaN,2024,5,2,1,...,-2.222222e-01,-0.222222,-0.222222,NaN,NaN,NaN,NaN,0.223307,2304.0,0.555556
3,40000892,1201,2024-03-01,2304.0,1.250000,NaN,2024,9,3,1,...,-6.250000e-01,-0.250000,-0.250000,NaN,NaN,NaN,NaN,0.235941,3686.4,1.000000
4,40000892,1201,2024-04-01,3686.4,1.600000,1.000000,2024,14,4,2,...,2.500000e-01,-0.125000,-0.125000,NaN,NaN,0.812500,0.250000,0.250237,2304.0,0.625000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4369,60009778,1204,2025-11-01,115.2,1.333333,0.421053,2025,44,11,4,...,-5.806452e-01,-0.092166,0.080758,0.602151,0.258065,0.903226,0.516129,0.750844,43.2,0.387097
4370,60009778,1204,2025-12-01,43.2,0.375000,1.000000,2025,49,12,4,...,-1.894737e-01,-0.274286,0.017225,0.800000,0.884211,1.010526,0.442105,0.794831,115.2,1.010526
4371,60009778,1204,2026-01-01,115.2,2.666667,0.470588,2026,1,1,1,...,-2.388938e-16,-0.053571,0.012238,0.458333,0.375000,0.875000,0.500000,0.842994,201.6,1.750000
4372,60009778,1204,2026-02-01,201.6,1.750000,2.333333,2026,5,2,1,...,6.168224e-01,-0.044860,0.011372,0.560748,0.560748,0.785047,0.280374,0.894074,201.6,1.570093
4373,60009778,1204,2026-03-01,201.6,1.000000,1.750000,2026,9,3,1,...,3.103448e-01,0.186207,0.012298,0.724138,0.517241,0.827586,0.362069,0.942867,NaN,NaN

In [26]:
df.columns

Index(['code', 'warehouse', 'month', 'value', 'momentum_ratio_1',
       'momentum_ratio_4', 'year', 'week_of_year', 'month_of_year',
       'quarter_of_year',
       ...
       'rolling_slope_3_scaled', 'rolling_slope_6_scaled',
       'rolling_slope_12_scaled', 'last_year_mean_3_scaled',
       'last_year_median_3_scaled', 'spike_prior_median_6_scaled',
       'spike_prior_mad_6_scaled', 'sample_weight', 'target_t_plus_1',
       'target_scaled_t_plus_1'],
      dtype='str', length=115)

In [ ]:
# Columns that end with "_scaled"
scaled_cols = [col for col in df.columns if col.endswith("_scaled")]

# Same column names without "_scaled"
original_cols_to_drop = [col.removesuffix("_scaled") for col in scaled_cols]

# Keep only those that actually exist in the original df
original_cols_to_drop = [col for col in original_cols_to_drop if col in df.columns]

# Drop them from df
df = df.drop(columns=original_cols_to_drop)

In [27]:
show_df_in_dtale(df)

c:\Users\jmi\AppData\Local\miniconda3\envs\time_series_auto\Lib\site-packages\dtale\utils.py:868: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data = data.reset_index(drop=drop_index)
2026-06-09 15:48:35,662 - INFO     - Executing shutdown...
2026-06-09 15:48:35,666 - INFO     - Not running with the Werkzeug Server, exiting by searching gc for BaseWSGIServer
c:\Users\jmi\AppData\Local\miniconda3\envs\time_series_auto\Lib\site-packages\dtale\utils.py:868: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data = data.reset_index(drop=drop_index)
2026-06-09 15:48:36,334 - WARNING  - Custom filtering enabled. Custom filters are vulnerable to code injection attacks, please only use in trusted environments.

D-Tale running on: http://PC-104:40000/dtale/main/1

2026-06-09 17:09:36,752 - INFO     - Executing shutdown due to inactivity...
2026-06-09 17:09:41,147 - INFO     - Executing shutdown...
2026-06-09 17:09:41,153 - INFO     - Not running with the Werkzeug Server, exiting by searching gc for BaseWSGIServer

#### **Predictions**

In [ ]:
#df_products = pd.read_excel("../../data/Lecta/raw/LECTA - Aquiles_products.xlsx")
df = pd.read_csv("../../results/lecta_catboost_predictions_month_h6_moderate_params.csv", sep=";")
df

,code,warehouse,datetime,train_val_test,momentum_ratio_1,momentum_ratio_4,year,week_of_year,month_of_year,quarter_of_year,...,last_year_median_3,spike_prior_median_6_scaled,spike_prior_median_6,spike_prior_mad_6_scaled,spike_prior_mad_6,target_original,target_scaled,prediction_catboost_scaled,prediction_catboost,horizon
0,40000892,1201,2023-12-01,train,NaN,NaN,2023,48,12,4,...,NaN,NaN,NaN,NaN,NaN,6912.0,1.875000,0.969754,3574.902137,1
1,40000892,1201,2023-12-01,train,NaN,NaN,2023,48,12,4,...,NaN,NaN,NaN,NaN,NaN,1843.2,0.500000,1.013803,3737.282915,2
2,40000892,1201,2023-12-01,train,NaN,NaN,2023,48,12,4,...,NaN,NaN,NaN,NaN,NaN,2304.0,0.625000,1.008493,3717.709863,3
3,40000892,1201,2023-12-01,train,NaN,NaN,2023,48,12,4,...,NaN,NaN,NaN,NaN,NaN,3686.4,1.000000,1.328370,4896.903032,4
4,40000892,1201,2023-12-01,train,NaN,NaN,2023,48,12,4,...,NaN,NaN,NaN,NaN,NaN,2304.0,0.625000,1.238872,4566.979089,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23782,60009778,1204,2025-12-01,train,0.375000,1.000000,2025,49,12,4,...,100.8,1.010526,115.2,0.442105,50.4,201.6,1.768421,0.930882,106.120505,2
23783,60009778,1204,2025-12-01,train,0.375000,1.000000,2025,49,12,4,...,100.8,1.010526,115.2,0.442105,50.4,201.6,1.768421,1.037583,118.284411,3
23784,60009778,1204,2026-01-01,train,2.666667,0.470588,2026,1,1,1,...,43.2,0.875000,100.8,0.500000,57.6,201.6,1.750000,0.934627,107.668999,1
23785,60009778,1204,2026-01-01,train,2.666667,0.470588,2026,1,1,1,...,43.2,0.875000,100.8,0.500000,57.6,201.6,1.750000,1.004909,115.765513,2
23786,60009778,1204,2026-02-01,train,1.750000,2.333333,2026,5,2,1,...,72.0,0.785047,100.8,0.280374,36.0,201.6,1.570093,0.859271,110.330414,1

In [13]:
show_df_in_dtale(df)

c:\Users\jmi\AppData\Local\miniconda3\envs\time_series_auto\Lib\site-packages\dtale\utils.py:868: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data = data.reset_index(drop=drop_index)
2026-06-05 11:18:19,498 - INFO     - Executing shutdown...
2026-06-05 11:18:19,500 - INFO     - Not running with the Werkzeug Server, exiting by searching gc for BaseWSGIServer
c:\Users\jmi\AppData\Local\miniconda3\envs\time_series_auto\Lib\site-packages\dtale\utils.py:868: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data = data.reset_index(drop=drop_index)
2026-06-05 11:18:20,307 - WARNING  - Custom filtering enabled. Custom filters are vulnerable to code injection attacks, please only use in trusted environments.

D-Tale running on: http://PC-104:40000/dtale/main/1

2026-06-05 12:30:42,722 - INFO     - Executing shutdown due to inactivity...